from enum import Enum


class ImageFile(Enum):
    """
    Paths to standard EV3 images.

    Note:
        Information: ACCEPT, BACKWARD, DECLINE, FORWARD, LEFT, NO_GO, QUESTION_MARK, RIGHT, STOP_1, STOP_2, THUMBS_DOWN, THUMBS_UP, WARNING

        LEGO&reg;: EV3, EV3_ICON

        Objects: TARGET

        Eyes: ANGRY, AWAKE, BOTTOM_LEFT, BOTTOM_RIGHT, CRAZY_1, CRAZY_2, DIZZY, DOWN, EVIL, KNOCKED_OUT, MIDDLE_LEFT, MIDDLE_RIGHT, NEUTRAL, PINCHED_LEFT, PINCHED_MIDDLE, PINCHED_RIGHT, SLEEPING, TIRED_LEFT, TIRED_MIDDLE, TIRED_RIGHT, UP, WINKING
    """
    ACCEPT = ...
    BACKWARD = ...
    DECLINE = ...
    FORWARD = ...
    LEFT = ...
    NO_GO = ...
    QUESTION_MARK = ...
    RIGHT = ...
    STOP_1 = ...
    STOP_2 = ...
    THUMBS_DOWN = ...
    THUMBS_UP = ...
    WARNING = ...

    EV3 = ...
    EV3_ICON = ...

    TARGET = ...

    ANGRY = ...
    AWAKE = ...
    BOTTOM_LEFT = ...
    BOTTOM_RIGHT = ...
    CRAZY_1 = ...
    CRAZY_2 = ...
    DIZZY = ...
    DOWN = ...
    EVIL = ...
    KNOCKED_OUT = ...
    MIDDLE_LEFT = ...
    MIDDLE_RIGHT = ...
    NEUTRAL = ...
    PINCHED_LEFT = ...
    PINCHED_MIDDLE = ...
    PINCHED_RIGHT = ...
    SLEEPING = ...
    TIRED_LEFT = ...
    TIRED_MIDDLE = ...
    TIRED_RIGHT = ...
    WINKING = ...
    UP = ...
