from enum import Enum


class Port(Enum):
    """
    Port on the programmable brick or hub.

    Note:
        Motor Ports: A, B, C, D
        Sensor Ports: S1, S2, S3, S4
    """
    A = ...
    B = ...
    C = ...
    D = ...
    S1 = ...
    S2 = ...
    S3 = ...
    S4 = ...
